# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean test jacocoTestReport

    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.8.1
      with:
        generate-branches-badge: true
        jacoco-csv-file: 'app/build/reports/jacoco/test/jacocoTestReport.csv'

    - name: Commit and push the coverage badges and summary file
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        if [[ `git status --porcelain .github/badges/*.svg` ]]; then
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .github/badges/*.svg
          git commit -m "Autogenerated JaCoCo coverage badges" *.svg
          git push
        fi

